extends Node

var PLAYER_HP = 5
var PLAYER_SPEED = 5000
var BLUEBAT_HP = 1
var BLUEBAT_SPEED = 2000
var BLUEEYE_HP = 1
var BLUEEYE_SPEED = 3000
var SHOOTING_SPEED_PLAYER = 100
var BULLET_RANGE = 800
var IS_PLAYER_DEAD = false
